FROM registry.fedoraproject.org/fedora-toolbox:41

RUN dnf update -y
RUN dnf -y group install development-tools

RUN dnf install -y jq

COPY packages /tmp/
RUN dnf install -y $(cat /tmp/packages | grep "^[^#;]")

RUN dnf clean all


