version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
      #docker_layer_caching: true
    resource_class: medium
    steps:
      - checkout
      - run: |
          sudo apt-get install -y docker-buildx-plugin
      - run: |
          echo "$GITHUB_ACCESS_KEY" | docker login -u seungjin --password-stdin ghcr.io
      - run: |
          docker build -f Fedora/39/Containerfile \
          -t ghcr.io/seungjin/toolbox:fedora ./Fedora/39/
      - run: |
          docker push ghcr.io/seungjin/toolbox:fedora
      - run: |
          docker build -f Debian/12/Containerfile \
          -t ghcr.io/seungjin/toolbox:debian ./Debian/12/
      - run: |
          docker push ghcr.io/seungjin/toolbox:debian
      #- run: |
      #    docker buildx imagetools create \
      #    -t ghcr.io/seungjin/toolbox:latest \
      #    ghcr.io/seungjin/toolbox:<<pipeline.parameters.image-tag>>

workflows:
  commit:
    jobs:
      - build
  daily:
    triggers:
      - schedule:
          cron: "30 18 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build

