version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
      #docker_layer_caching: true
    resource_class: medium
    steps:
      - checkout
      - run: |
          sudo apt-get install -y docker-buildx-plugin
      - run: |
          echo "$GITHUB_ACCESS_KEY" | docker login -u seungjin --password-stdin ghcr.io
      - run: |
          docker build -f Fedora/40/Containerfile \
          -t ghcr.io/seungjin/mytoolbox:fedora ./Fedora/40/
          docker push ghcr.io/seungjin/mytoolbox:fedora
      - run: |
          docker build -f Fedora/rawhide/Containerfile \
          -t ghcr.io/seungjin/mytoolbox:fedora-rawhide ./Fedora/rawhide/
          docker push ghcr.io/seungjin/mytoolbox:fedora-rawhide          
      - run: |
          docker build -f Debian/12/Containerfile \
          -t ghcr.io/seungjin/mytoolbox:debian ./Debian/12/
          docker push ghcr.io/seungjin/mytoolbox:debian          
      - run: |
          docker build -f Debian/unstable/Containerfile \
          -t ghcr.io/seungjin/mytoolbox:debian-unstable ./Debian/unstable/
          docker push ghcr.io/seungjin/mytoolbox:debian-unstable          
      - run: |
          docker build -f DevContainer/Containerfile.debian \
          -t ghcr.io/seungjin/codespace:debian ./DevContainer/
          docker push ghcr.io/seungjin/codespace:debian
      - run: |
          docker build -f Debian-guix/Containerfile \
          -t ghcr.io/seungjin/debian-guix:latest ./Debian-guix/
          docker push ghcr.io/seungjin/debian-guix:latest
      #- run: |
      #    docker buildx imagetools create \
      #    -t ghcr.io/seungjin/mytoolbox:latest \
      #    ghcr.io/seungjin/mytoolbox:<<pipeline.parameters.image-tag>>

workflows:
  commit:
    jobs:
      - build
  daily:
    triggers:
      - schedule:
          cron: "30 18 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build

