version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
      #docker_layer_caching: true
    resource_class: medium
    steps:
      - checkout
      - run: |
          sudo apt-get install -y docker-buildx-plugin
      - run: |
          echo "$GITHUB_ACCESS_KEY" | docker login -u seungjin --password-stdin ghcr.io
      - run: |
          docker build -f Containerfile \
          -t ghcr.io/seungjin/mytoolbox:<<pipeline.trigger_parameters.circleci.event_time>> .
      - run: |
          docker push ghcr.io/seungjin/mytoolbox:<<pipeline.trigger_parameters.circleci.event_time>>
      - run: |
          docker buildx imagetools create \
          -t ghcr.io/seungjin/mytoolbox:latest \
          ghcr.io/seungjin/mytoolbox:<<pipeline.trigger_parameters.circleci.event_time>>

workflows:
  commit:
    jobs:
      - build
  daily:
    triggers:
      - schedule:
          cron: "30 18 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build
