version: 2.1

parameters:
  image-tag:
    type: string
    default: ${date '+%Y%m%d_%H%M%S'}

jobs:
  build:
    machine:
      image: ubuntu-2204:current
      #docker_layer_caching: true
    resource_class: medium
    steps:
      - checkout
      - run: |
          sudo apt-get install -y docker-buildx-plugin
      - run: |
          echo "$GITHUB_ACCESS_KEY" | docker login -u seungjin --password-stdin ghcr.io
      - run: |
          docker build -f Containerfile \
          -t ghcr.io/seungjin/mytoolbox:<<pipeline.parameters.image-tag>> .
      - run: |
          docker push ghcr.io/seungjin/mytoolbox:<<pipeline.parameters.image-tag>>
      - run: |
          docker buildx imagetools create \
          -t ghcr.io/seungjin/mytoolbox:latest \
          ghcr.io/seungjin/mytoolbox:<<pipeline.parameters.image-tag>>

workflows:
  commit:
    jobs:
      - build
  daily:
    triggers:
      - schedule:
          cron: "30 18 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build
