#FROM docker.io/library/debian:12
FROM quay.io/toolbx-images/debian-toolbox:13

RUN apt update && apt upgrade -y && apt-get -y install wget curl gpg jq

#RUN wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
#RUN install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
#RUN sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
#RUN rm -f packages.microsoft.gpg

# RUN wget -qO - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg \
#     | gpg --dearmor \
#     | dd of=/usr/share/keyrings/vscodium-archive-keyring.gpg
# RUN echo 'deb [ signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg ] https://download.vscodium.com/debs vscodium main' \
#     | tee /etc/apt/sources.list.d/vscodium.list

# https://github.com/VSCodium/vscodium/issues/1910
#RUN export CODIUM_VER=$(curl -sL https://api.github.com/repos/VSCodium/vscodium/releases/latest | jq -r ".tag_name"); \
#    wget -P /tmp https://github.com/VSCodium/vscodium/releases/download/${CODIUM_VER}/codium_${CODIUM_VER}_amd64.deb; \
#    wget -P /tmp  https://github.com/VSCodium/vscodium/releases/download/${CODIUM_VER}/codium_${CODIUM_VER}_amd64.deb.sha256 ;\
#    cd /tmp ;\
#    if [ test $(sha256sum -c --status codium_${CODIUM_VER}_amd64.deb.sha256)  ]; then apt-get -y install ./codium_${CODIUM_VER}_amd64.deb; fi;\
#    rm -fr /tmp/codium-*

RUN apt install -y apt-transport-https && apt update

COPY packages /tmp/packages
RUN apt-get install -y $(cat /tmp/packages | grep "^[^#;]")


