FROM registry.fedoraproject.org/fedora-toolbox:rawhide

RUN dnf update -y
RUN dnf -y group install development-tools

RUN dnf install -y jq

#RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc && sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'

RUN rpmkeys --import https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg
RUN printf "[gitlab.com_paulcarroty_vscodium_repo]\nname=download.vscodium.com\nbaseurl=https://download.vscodium.com/rpms/\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg\nmetadata_expire=1h" | sudo tee -a /etc/yum.repos.d/vscodium.repo
# https://github.com/VSCodium/vscodium/issues/1910
#RUN export CODIUM_VER=$(curl -sL https://api.github.com/repos/VSCodium/vscodium/releases/latest | jq -r ".tag_name"); \
#    wget -P /tmp https://github.com/VSCodium/vscodium/releases/download/$CODIUM_VER/codium-$CODIUM_VER-el7.x86_64.rpm; \
#    wget -P /tmp  https://github.com/VSCodium/vscodium/releases/download/$CODIUM_VER/codium-$CODIUM_VER-el7.x86_64.rpm.sha256 ;\
#    cd /tmp ;\
#    if [ test $(sha256sum -c --status codium-$CODIUM_VER-el7.x86_64.rpm.sha256)  ]; then dnf install -y codium-$CODIUM_VER-el7.x86_64.rpm; fi;\
#    rm -fr /tmp/codium-*

COPY packages /tmp/
RUN dnf install -y $(cat /tmp/packages | grep "^[^#;]")

RUN dnf clean all
